name: dbt_course_ecommerce
version: 1.0.0
config-version: 2

profile: dbt_course

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


models:
    dbt_course_ecommerce:
        +materialized: table
        marts:
            finance:
                +group: ecommerce
                +access: private